export const INIT_AIRCRAFT = "INIT_AIRCRAFT";
export const FETCH_AIRCRAFT_SUCCESS = "FETCH_AIRCRAFT_SUCCESS";
export const FETCH_AIRCRAFT_FAIL = "FETCH_AIRCRAFT_FAIL";
export const CLEAR_SELECTED_AIRCRAFTS = "CLEAR_SELECTED_AIRCRAFTS";

export const INIT_ROTATION = "INIT_ROTATION";

export const ADD_FLIGHT = "ADD_FLIGHT";
export const REMOVE_FLIGHT = "REMOVE_FLIGHT";

export const INIT_FLIGHT = "INIT_FLIGHT";
export const FETCH_FLIGHT_SUCCESS = "FETCH_FLIGHT_SUCCESS";
export const FETCH_FLIGHT_FAIL = "FETCH_FLIGHT_FAIL";
export const SELECTED_FLIGHT = "SELECTED_FLIGHT";
export const DE_SELECTED_FLIGHT = "DE_SELECTED_FLIGHT";
export const CLEAR_SELECTED_FLIGHT = "CLEAR_SELECTED_FLIGHT";
